foreground #adadad
background #010101
selection_foreground #3B3B3B
selection_background #2B2B2B
cursor #adadad
active_border_color #adadad
inactive_border_color #010101
active_tab_foreground #adadad
active_tab_background #010101
inactive_tab_foreground #adadad
inactive_tab_background #010101
