foreground #A0A3A3
background #181C1D
selection_foreground #754C39
selection_background #3B4348
cursor #A0A3A3
active_border_color #A0A3A3
inactive_border_color #181C1D
active_tab_foreground #A0A3A3
active_tab_background #181C1D
inactive_tab_foreground #A0A3A3
inactive_tab_background #181C1D
