[urgency_low]
    background = "{color14}"
    foreground = "{color0}"

[urgency_normal]
    background = "{color6}"
    foreground = "{color0}"

[urgency_critical]
    background = "{color1}"
    foreground = "{color15}"
