# Colors (Base16 Default Dark)
colors:
  # Default colors
  primary:
    background: "#034240"
    foreground: "#96b7b6"

  cursor:
    text: "#96b7b6"
    cursor: "#96b7b6"

  # Normal colors
  normal:
    black:   "#034240"
    red:     "#156060"
    green:   "#265559"
    yellow:  "#476f73"
    blue:    "#15413d"
    magenta: "#5ca1a8"
    cyan:    "#b3f3f8"
    white:   "#96b7b6"

  # Bright colors
  bright:
    black:   "#5b9998"
    red:     "#2fa7a7"
    green:   "#3b9ba3"
    yellow:  "#51b1ba"
    blue:    "#328d84"
    magenta: "#68cfd9"
    cyan:    "#c0fbff"
    white:   "#ccd9d8"
