# ==============================================
# HYPRLAND MAIN CONFIGURATION
# ==============================================

# Definir variáveis comuns
$mainMod = SUPER

# Sourcear os arquivos de configuração específicos
source = ~/.config/hypr/animations.conf
source = ~/.config/hypr/decoration.conf
source = ~/.config/hypr/env.conf
source = ~/.config/hypr/general.conf
source = ~/.config/hypr/gestures.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/keybindings.conf
source = ~/.config/hypr/layout.conf
source = ~/.config/hypr/misc.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/startup.conf
source = ~/.config/hypr/windowrules.conf
