# Perfil da MANHÃ (ativação às 7:00)
profile {
    time = 7:00
    identity = true  # Cores normais (filtro OFF)
}

# Perfil da NOITE (ativação às 21:00)
profile {
    time = 21:00
    temperature = 4500
    gamma = 1.0
}

# Perfil de "RESET" para o início do dia (ativação às 6:59)
profile {
    time = 6:59
    identity = true
}
