general {
    lock_cmd = pidof hyprlock || hyprlock       # evita múltiplas instâncias
    before_sleep_cmd = loginctl lock-session    # trava antes de suspender
    after_sleep_cmd = hyprctl dispatch dpms on  # garante que a tela ligue ao voltar
}

# 1. DIM: Diminui o brilho aos 9 minutos (aviso visual antes de travar)
listener {
    timeout = 240                                
    on-timeout = brightnessctl -s set 10         
    on-resume = brightnessctl -r                 
}

# 2. LOCK: Trava a tela aos 10 minutos
# Isso ativará o seu hyprlock com todos os widgets que você configurou
listener {
    timeout = 300                                
    on-timeout = loginctl lock-session           
}

# 3. KEYBOARD: Apaga o teclado junto com o bloqueio
listener { 
    timeout = 300                                          
    on-timeout = brightnessctl -sd rgb:kbd_backlight set 0 
    on-resume = brightnessctl -rd rgb:kbd_backlight     # restaura a luz do teclado
}

# 4. DPMS: Desliga o monitor 1 minuto após travar (economia de energia)
listener {
    timeout = 360                                
    on-timeout = hyprctl dispatch dpms off       
    on-resume = hyprctl dispatch dpms on         
}

# 5. SUSPEND: Suspende o sistema após 30 minutos de inatividade
listener {
    timeout = 900                                
    on-timeout = systemctl suspend                
}
