# ==============================================
# MONITOR CONFIGURATION
# ==============================================
monitor = eDP-1, 1366x768@60.00400, 0x0, 1.00 #notebook
monitor = HDMI-A-1, 1920x1080@60, 1366x0, 1 #projetor à direita
