# ==============================================
# AUTOSTART APPLICATIONS
# ==============================================
exec-once = nm-applet --indicator
exec-once = ~/.config/hypr/scripts/launch-waybar.sh
#exec-once = mako
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = foot --server
exec-once = hypridle
exec-once = apply-gsettings
exec-once = dunst

# Para aplicativos GTK
exec = gsettings set org.gnome.desktop.interface gtk-theme "Adwaita-dark"
exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"

# Inicializar hyprpaper
exec-once = wpaperd

# Clipboard Manager
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
