# ==============================================
# WINDOW RULES
# ==============================================
# Floating windows
windowrule = float, title:(^(kitty)$)
windowrule = float, title:(^(garuda-assistant)$)
windowrule = float, title:(^(garuda-boot-options)$)
windowrule = float, title:(^(garuda-boot-repair)$)
windowrule = float, title:(^(garuda-gamer)$)
windowrule = float, title:(^(garuda-network-assistant)$)
windowrule = float, title:(^(garuda-settings-manager)$)
windowrule = float, title:(^(garuda-welcome)$)
windowrule = float, title:(^(calamares)$)

# Opacity rules
windowrule = opacity 0.85 override 0.85 override, title:(^(thunar)$)
windowrule = opacity 0.85 override 0.85 override, title:(^(gedit)$)
windowrule = opacity 0.85 override 0.85 override, title:(^(catfish)$)
windowrule = stayfocused, title:(^(wofi)$)
windowrulev2 = opacity 0.85 0.85, floating:1

# Blur effects
layerrule = blur, waybar
layerrule = ignorezero, waybar
blurls = wofi
blurls = thunar
blurls = gedit
blurls = gtk-layer-shell
blurls = catfish