
# Overview setting
hotarea_size=5
enable_hotarea=1
hotarea_corner=1
ov_tab_mode=0
ov_no_resize=0
overviewgappi=10
overviewgappo=20

# Overview Jump Mode (Jump Text Configuration)
jump_label_decorate_fg_color=0x8aadf4ff
jump_label_decorate_bg_color=0x00000000
jump_label_decorate_border_color=0xed8796ff
jump_label_decorate_border_width=2
jump_label_decorate_corner_radius=0
jump_label_decorate_padding_x=13
jump_label_decorate_padding_y=5
jump_label_decorate_font_desc = JetBrains Mono ExtraBold 18
