windowrule=unfocused_opacity:1.0,focused_opacity:1.0,appid:^mpv$
windowrule=unfocused_opacity:1.0,focused_opacity:1.0,appid:^kitty$
windowrule=unfocused_opacity:1.0,focused_opacity:1.0,appid:^firefox$
windowrule=tags:2,monitor:eDP-1,appid:obs
windowrule=tags:6,monitor:HDMI-A-1,appid:firefox
windowrule=tags:7,monitor:HDMI-A-1,appid:org.telegram.desktop
windowrule=tags:8,monitor:HDMI-A-1,appid:mpv
windowrule=force_fakemaximize:1,appid:firefox
windowrule=force_fakemaximize:1,appid:org.telegram.desktop
windowrule=allow_csd:1,appid:firefox
windowrule=title:satty,isfloating:1
windowrule=isfloating:1,width:800,height:600,appid:blueman-manager
windowrule=isfloating:1,width:800,height:600,appid:localsend
windowrule=isfloating:1,width:800,height:600,appid:nmtui
windowrule=isfloating:1,width:800,height:600,appid:bluetui
windowrule=isfloating:1,width:600,height:800,appid:galculator
windowrule=isfloating:1,width:800,height:600,appid:pavucontrol
#windowrule=isfloating:1,width:800,height:600,appid:thunar
windowrule=isfloating:1,width:800,height:600,appid:thunar,title:.*Rename.*
windowrule=isoverlay:1,isfloating:1,appid:thunar,title:.*Properties.*
windowrule=isoverlay:1,isfloating:1,appid:thunar,title:.*Preferences.*
windowrule=isoverlay:1,isfloating:1,appid:thunar,title:.*Custom.*
windowrule=isoverlay:1,isfloating:1,appid:thunar,title:.*Configure.*
windowrule=isfloating:1,isnoshadow:1,ignore_maximize:1,ignore_minimize:1,width:480,height:270,appid:firefox,title:Picture-in-Picture
windowrule=isfloating:1,noopenmaximized:1,appid:firefox,title:^(Save|Open|Export)
windowrule=isfloating:1,noopenmaximized:1,title:^(Open File|Save File|Preferences|Properties|About)
windowrule=appid:org.kde.kdeconnect.daemon,offsety:90%,offsetx:98%,isfloating:1,allow_csd:0,width:500,height:280
windowrule=appid:org.kde.kdeconnect.handler,offsety:90%,offsetx:98%,isfloating:1,allow_csd:0,width:500,height:280
windowrule=appid:org.kde.kdeconnect.sms,offsety:96%,offsetx:98%,isfloating:1,width:1000,height:580
windowrule=appid:dashboard,offsety:96%,offsetx:98%,isfloating:1,width:640,height:340
windowrule=appid:clipboard,offsety:96%,offsetx:-98%,isfloating:1,width:960,height:560
windowrule=appid:org.kde.kdeconnect.app,offsety:96%,offsetx:98%,isfloating:1,width:980,height:575

# layer rule
layerrule=noblur:1,noanim:1,layer_name:selection
layerrule=noblur:1,noanim:1,layer_name:dimland_layer
layerrule=animation_type_open:zoom,layer_name:launcher
layerrule=animation_type_close:zoom,layer_name:launcher
layerrule=noanim:1,noblur:1,noshadow:1,layer_name:hyprpicker
layerrule=noanim:1,layer_name:showkeys
