windowrule=focused_opacity:1.0,appid:^mpv$
windowrule=focused_opacity:1.0,appid:^vlc$
windowrule=focused_opacity:0.8,appid:^kitty$
windowrule=focused_opacity:1.0,appid:firefox$
windowrule=tags:2,monitor:eDP-1,appid:obs
windowrule=tags:5,monitor:eDP-1,appid:dashboard
windowrule=tags:6,monitor:HDMI-A-1,appid:firefox
windowrule=tags:7,monitor:HDMI-A-1,appid:org.telegram.desktop
windowrule=tags:8,monitor:HDMI-A-1,appid:mpv
windowrule=tags:8,monitor:HDMI-A-1,appid:vlc
windowrule=force_fakemaximize:1,appid:firefox
windowrule=force_fakemaximize:1,appid:org.telegram.desktop
windowrule=allow_csd:0,appid:firefox
windowrule=title:satty,isfloating:1
windowrule=title:Authentication required,isfloating:1
windowrule=title:Keybindings,isfloating:1
windowrule=title:Rename*,isfloating:1
windowrule=title:Compressing*,isfloating:1
windowrule=title:File Already Exists*,isfloating:1
windowrule=title:Extracting Files*,isfloating:1
windowrule=title:File Operation Progress*,isfloating:1
windowrule=title:Confirm to replace files*,isfloating:1
windowrule=appid:launcher,offsety:100%,offsetx:0%,isfloating:1,width:580,height:340
windowrule=isfloating:1,offsety:0%,offsetx:0%,width:800,height:600,appid:blueman-manager
windowrule=isfloating:1,offsety:0%,offsetx:0%,width:800,height:600,appid:localsend
windowrule=isfloating:1,offsety:0%,offsetx:0%,width:800,height:600,appid:nmtui
windowrule=isfloating:1,offsety:0%,offsetx:0%,width:800,height:600,appid:bluetui
windowrule=isfloating:1,offsety:0%,offsetx:0%,width:600,height:800,appid:galculator
windowrule=isfloating:1,width:800,height:600,appid:pavucontrol
#windowrule=isfloating:1,offsety:0%,offsetx:0%,width:800,height:800,appid:thunar
windowrule=offsety:96%,offsetx:98%,isnoborder:1,isopensilent:1,isoverlay:1,isfloating:1,width:440,height:220,title:Picture-in-Picture
windowrule=offsety:96%,offsetx:98%,isnoborder:1,isopensilent:1,isoverlay:1,isfloating:1,width:440,height:220,title:Picture in picture
windowrule=isfloating:1,noopenmaximized:1,appid:firefox,title:^(Save|Open|Export)
windowrule=isfloating:1,noopenmaximized:1,title:^(Open File|Save File|Preferences|Properties|About)
windowrule=appid:clipboard,offsety:96%,offsetx:-98%,isfloating:1,width:960,height:560

# layer rule
layerrule=noblur:1,noanim:1,layer_name:selection
layerrule=noblur:1,noanim:1,layer_name:dimland_layer
layerrule=animation_type_open:zoom,layer_name:launcher
layerrule=animation_type_close:zoom,layer_name:launcher
layerrule=noanim:1,noblur:1,noshadow:1,layer_name:hyprpicker
layerrule=noanim:1,layer_name:showkeys
