[general]
out_dir = ~/.cache/cwal/
backend = cwal
script_path = ~/.local/bin/post-cwal.sh

[options]
alpha = 1.00
saturation = 0.00
contrast = 1.00
mode = dark
cols16_mode = darken
skip_cursor = false

[random]
random_dir = ~/.config/wallpapers

[links]
## Omit the command to only sync the file
colors-kitty.conf = ~/.config/kitty/current-theme.conf